<a href="https://colab.research.google.com/github/affled/LED1703/blob/main/request2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [109]:
import pandas as pd
import numpy as np

In [177]:
df = pd.read_excel('/content/dar1.xlsx', header = 1).drop(columns=['Unnamed: 0', 'Unnamed: 13', 'Unnamed: 15'])
df.head()

/usr/local/lib/python3.11/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

,В/П,№ рейса,Код АП,Маршрут,Борт,Время рейса план,Actual data time,ONB and OFB,Компоновка,Вместимость,...,Кл.1,Кл.2,Кл.3,"МВМ, тонн",Тип ВС,АВК,Направление,Катег,Baggage Weight,Spot Number
0,В,DP 204,VKO,ВНУКОВО,RA73232,2024-12-31 19:30:00,2025-01-01 00:01:00,2024-12-31 23:53:00,Y189,189.0,...,0.0,0.0,115.0,75.296,73H,1.0,Domestic,J,143.0,106A
1,В,FZ 992,DXB,ДУБАЙ,A6FMJ,2025-01-01 00:25:00,2025-01-01 01:03:00,2025-01-01 00:50:00,174,166.0,...,0.0,0.0,132.0,82.190,7M8,1.0,International,J,1396.0,104B
2,В,2S 204,AYT,АНТАЛЬЯ,TCGRA,2025-01-01 01:30:00,2025-01-01 02:05:00,2025-01-01 01:46:00,Y345,312.0,...,0.0,0.0,342.0,233.000,332,1.0,International,J,3881.0,105
3,П,JU 124,BEG,БЕЛГРАД,YUAPN,2025-01-01 04:05:00,2025-01-01 04:06:00,2025-01-01 04:11:00,12J126Y,144.0,...,0.0,0.0,66.0,70.000,319,1.0,International,J,1159.0,104B
4,В,SU 734,SSH,ШАРМ-ЭЛЬ-ШЕЙХ,73785,2025-01-01 04:00:00,2025-01-01 04:19:00,2025-01-01 04:04:00,C28Y268,296.0,...,0.0,23.0,260.0,230.000,333,1.0,International,J,3243.0,103

In [161]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11271 entries, 0 to 11270
Data columns (total 24 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   В/П                   11269 non-null  object
 1   № рейса               11269 non-null  object
 2   Код АП                11268 non-null  object
 3   Маршрут               11242 non-null  object
 4   Борт                  11268 non-null  object
 5   Время рейса план      11268 non-null  datetime64[ns]
 6   Actual data time      11269 non-null  object
 7   ONB and OFB           11268 non-null  datetime64[ns]
 8   Компоновка            11252 non-null  object
 9   Вместимость           11268 non-null  float64
 10  Обслужено пассажиров  11267 non-null  float64
 11  Взр                   11269 non-null  float64
 12  Дети                  11269 non-null  float64
 13  До 2-лет              11269 non-null  float64
 14  Кл.1                  11269 non-null  float64
 15  Кл.2                  11269 non-null  float64
 16  Кл.3                  11269 non-null  float64
 17  МВМ, тонн             11269 non-null  float64
 18  Тип ВС                11268 non-null  object
 19  АВК                   11268 non-null  float64
 20  Направление           11268 non-null  object
 21  Катег                 11268 non-null  object
 22  Baggage Weight        11243 non-null  float64
 23  Spot Number           11268 non-null  object
dtypes: datetime64[ns](2), float64(11), object(11)
memory usage: 2.1+ MB

In [97]:
df.isna().sum()

В/П                      2
№ рейса                  2
Код АП                   3
Маршрут                 29
Борт                     3
Время рейса план         3
Actual data time         2
ONB and OFB              3
Компоновка              19
Вместимость              3
Обслужено пассажиров     4
Взр                      2
Дети                     2
До 2-лет                 2
Кл.1                     2
Кл.2                     2
Кл.3                     2
МВМ, тонн                2
Тип ВС                   3
АВК                      3
Направление              3
Катег                    3
Baggage Weight          28
Spot Number              3
dtype: int64

In [98]:
df.select_dtypes(include=['object']).describe()

,В/П,№ рейса,Код АП,Маршрут,Борт,Actual data time,Компоновка,Тип ВС,Направление,Катег,Spot Number
count,11269,11269,11268,11242,11268,11269,11252,11268,11268,11268,11268
unique,3,821,102,101,628,10765,200,30,2,4,106
top,В,DP 572,SVO,ШЕРЕМЕТЬЕВО,RA73651,2025-01-18 22:57:00,C12Y75,SU9,Domestic,J,106A
freq,5642,32,1703,1703,165,3,2360,3378,9370,9667,553

In [191]:
df.select_dtypes(include=['float64']).describe()

,Вместимость,Обслужено пассажиров,Взр,Дети,До 2-лет,Кл.1,Кл.2,Кл.3,"МВМ, тонн",АВК,Baggage Weight
count,11268.000000,1.126700e+04,1.126900e+04,11269.000000,11269.000000,11269.000000,11269.000000,1.126900e+04,11269.000000,11268.0,11243.000000
mean,147.469027,2.539123e+02,2.398177e+02,13.873281,1.851273,0.023250,6.928920,2.440838e+02,142.676610,1.0,745.221382
std,56.719575,1.347482e+04,1.272796e+04,736.331751,98.262639,1.258056,367.770554,1.295440e+04,7572.382994,0.0,792.998891
min,19.000000,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000e+00,17.200000,1.0,-690.000000
25%,93.000000,8.400000e+01,8.000000e+01,2.000000,0.000000,0.000000,0.000000,7.400000e+01,45.880000,1.0,295.000000
50%,148.000000,1.230000e+02,1.170000e+02,5.000000,0.000000,0.000000,1.000000,1.170000e+02,73.500000,1.0,492.000000
75%,189.000000,1.710000e+02,1.610000e+02,9.000000,1.000000,0.000000,6.000000,1.690000e+02,77.337000,1.0,844.000000
max,457.000000,1.430415e+06,1.351253e+06,78169.000000,10431.000000,131.000000,39041.000000,1.375290e+06,803911.357000,1.0,11106.000000

In [100]:
group = df[['Код АП']].value_counts(normalize=True)*100
round(group.head(10),1)

Код АП
SVO       15.1
VKO        9.3
KGD        5.9
AER        3.9
KZN        3.2
MMK        2.9
SVX        2.8
ARH        2.8
KUF        2.4
UFA        2.2
Name: proportion, dtype: float64

In [176]:
domestic_flights = df[df['Направление'] == 'Domestic']
group = df[['Код АП']].value_counts(normalize=True)*100
round(group.head(10),1)

Код АП
SVO       15.1
VKO        9.3
KGD        5.9
AER        3.9
KZN        3.2
MMK        2.9
SVX        2.8
ARH        2.8
KUF        2.4
UFA        2.2
Name: proportion, dtype: float64

In [178]:
domestic_flights = df[df['Направление'] == 'Domestic']
international_flights = df[df['Направление'] == 'International']
group_1 = domestic_flights[['Код АП']].value_counts()
roup_2 = international_flights[['Код АП']].value_counts()

group_1.head(1)

Код АП
SVO       1703
Name: count, dtype: int64

In [204]:
df[((df['Катег'] == 'C') & (df['Маршрут'] == 'САЛЕХАРД'))]

,В/П,№ рейса,Код АП,Маршрут,Борт,Время рейса план,Actual data time,ONB and OFB,Компоновка,Вместимость,...,Кл.1,Кл.2,Кл.3,"МВМ, тонн",Тип ВС,АВК,Направление,Катег,Baggage Weight,Spot Number
8941,П,YC 9715,SLY,САЛЕХАРД,67219,2025-01-24 19:00:00,2025-01-24 19:30:00,2025-01-24 19:34:00,14,19.0,...,0.0,6.0,0.0,24.04,CR2,1.0,Domestic,C,40.0,262
9511,В,YC 9716,SLY,САЛЕХАРД,RA67219,2025-01-26 14:00:00,2025-01-26 14:04:00,2025-01-26 14:02:00,C14,19.0,...,0.0,0.0,5.0,24.04,CR2,1.0,Domestic,C,180.0,262

In [205]:
group = df[((df['Катег'] == 'C') & (df['Маршрут'] == 'САЛЕХАРД'))]
group.sort_values(by="Baggage Weight", ascending=True)

,В/П,№ рейса,Код АП,Маршрут,Борт,Время рейса план,Actual data time,ONB and OFB,Компоновка,Вместимость,...,Кл.1,Кл.2,Кл.3,"МВМ, тонн",Тип ВС,АВК,Направление,Катег,Baggage Weight,Spot Number
8941,П,YC 9715,SLY,САЛЕХАРД,67219,2025-01-24 19:00:00,2025-01-24 19:30:00,2025-01-24 19:34:00,14,19.0,...,0.0,6.0,0.0,24.04,CR2,1.0,Domestic,C,40.0,262
9511,В,YC 9716,SLY,САЛЕХАРД,RA67219,2025-01-26 14:00:00,2025-01-26 14:04:00,2025-01-26 14:02:00,C14,19.0,...,0.0,0.0,5.0,24.04,CR2,1.0,Domestic,C,180.0,262

In [256]:
# хотел сократить числа до 1 знака после запятой, но не вышло grouped_vm_vp["МВМ, тонн"] = grouped_vm_vp["МВМ, тонн"].round(0) и по вместимости аналогично, что пошло не так? пробовал в числа преоброзовать, тоже не пошло

df.groupby(['Направление', 'Тип ВС'])[["МВМ, тонн", "Вместимость"]].mean()

                       МВМ, тонн  Вместимость
Направление   Тип ВС
Domestic      319      70.077146   128.208817
              320      76.406040   158.302013
              321      89.170213   215.638298
              32A      75.500000   151.274538
              32B      91.113636   189.848485
              32N      75.213415   176.170732
              32Q      93.520468   237.549708
              332     233.000000   361.476190
              333     233.365385   298.692308
              735      56.850000   126.000000
              73G      70.080000   140.000000
              73H      76.871667   188.229361
              73W      67.269776   148.000000
              77W     325.074000   420.333333
              789     250.836000   290.000000
              A26      24.000000    40.000000
              CR1      24.040000    50.000000
              CR2      24.034194    49.500000
              E90      50.300000   110.000000
              S9S      45.880000    93.000000
              SU9      46.103326    90.282105
              YK4      17.200000    30.000000
International 319      69.751412   132.700565
              320      76.225664   159.610619
              321      89.000000   190.000000
              32A      75.184211   148.000000
              32B      89.533333   214.000000
              32N      76.964912   181.947368
              32Q      93.510730   223.879828
              332     234.245902   287.278689
              333     233.238938   302.725664
              733      63.134000   148.000000
              735      56.233333   123.000000
              739      85.139000   184.000000
              73H      78.344777   174.542510
              73W      69.512500   120.000000
              752     115.892000   238.000000
              763     186.313000   313.750000
              772     289.448500   429.500000
              77W     351.030000   354.000000
              789     243.900960   290.000000
              7M8      82.190000   166.848485
              E75      38.790000    76.000000
              E95      50.790000   107.000000
              SU9      49.450000   100.000000