<a href="https://colab.research.google.com/github/affled/LED1703/blob/main/request2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [109]:
import pandas as pd
import numpy as np

In [160]:
df = pd.read_excel('/content/dar1.xlsx', header = 1).drop(columns=['Unnamed: 0', 'Unnamed: 13', 'Unnamed: 15'])
df.head()

/usr/local/lib/python3.11/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

,В/П,№ рейса,Код АП,Маршрут,Борт,Время рейса план,Actual data time,ONB and OFB,Компоновка,Вместимость,...,Кл.1,Кл.2,Кл.3,"МВМ, тонн",Тип ВС,АВК,Направление,Катег,Baggage Weight,Spot Number
0,В,DP 204,VKO,ВНУКОВО,RA73232,2024-12-31 19:30:00,2025-01-01 00:01:00,2024-12-31 23:53:00,Y189,189.0,...,0.0,0.0,115.0,75.296,73H,1.0,Domestic,J,143.0,106A
1,В,FZ 992,DXB,ДУБАЙ,A6FMJ,2025-01-01 00:25:00,2025-01-01 01:03:00,2025-01-01 00:50:00,174,166.0,...,0.0,0.0,132.0,82.190,7M8,1.0,International,J,1396.0,104B
2,В,2S 204,AYT,АНТАЛЬЯ,TCGRA,2025-01-01 01:30:00,2025-01-01 02:05:00,2025-01-01 01:46:00,Y345,312.0,...,0.0,0.0,342.0,233.000,332,1.0,International,J,3881.0,105
3,П,JU 124,BEG,БЕЛГРАД,YUAPN,2025-01-01 04:05:00,2025-01-01 04:06:00,2025-01-01 04:11:00,12J126Y,144.0,...,0.0,0.0,66.0,70.000,319,1.0,International,J,1159.0,104B
4,В,SU 734,SSH,ШАРМ-ЭЛЬ-ШЕЙХ,73785,2025-01-01 04:00:00,2025-01-01 04:19:00,2025-01-01 04:04:00,C28Y268,296.0,...,0.0,23.0,260.0,230.000,333,1.0,International,J,3243.0,103

In [161]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11271 entries, 0 to 11270
Data columns (total 24 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   В/П                   11269 non-null  object
 1   № рейса               11269 non-null  object
 2   Код АП                11268 non-null  object
 3   Маршрут               11242 non-null  object
 4   Борт                  11268 non-null  object
 5   Время рейса план      11268 non-null  datetime64[ns]
 6   Actual data time      11269 non-null  object
 7   ONB and OFB           11268 non-null  datetime64[ns]
 8   Компоновка            11252 non-null  object
 9   Вместимость           11268 non-null  float64
 10  Обслужено пассажиров  11267 non-null  float64
 11  Взр                   11269 non-null  float64
 12  Дети                  11269 non-null  float64
 13  До 2-лет              11269 non-null  float64
 14  Кл.1                  11269 non-null  float64
 15  Кл.2                  11269 non-null  float64
 16  Кл.3                  11269 non-null  float64
 17  МВМ, тонн             11269 non-null  float64
 18  Тип ВС                11268 non-null  object
 19  АВК                   11268 non-null  float64
 20  Направление           11268 non-null  object
 21  Катег                 11268 non-null  object
 22  Baggage Weight        11243 non-null  float64
 23  Spot Number           11268 non-null  object
dtypes: datetime64[ns](2), float64(11), object(11)
memory usage: 2.1+ MB

In [97]:
df.isna().sum()

В/П                      2
№ рейса                  2
Код АП                   3
Маршрут                 29
Борт                     3
Время рейса план         3
Actual data time         2
ONB and OFB              3
Компоновка              19
Вместимость              3
Обслужено пассажиров     4
Взр                      2
Дети                     2
До 2-лет                 2
Кл.1                     2
Кл.2                     2
Кл.3                     2
МВМ, тонн                2
Тип ВС                   3
АВК                      3
Направление              3
Катег                    3
Baggage Weight          28
Spot Number              3
dtype: int64

In [98]:
df.select_dtypes(include=['object']).describe()

,В/П,№ рейса,Код АП,Маршрут,Борт,Actual data time,Компоновка,Тип ВС,Направление,Катег,Spot Number
count,11269,11269,11268,11242,11268,11269,11252,11268,11268,11268,11268
unique,3,821,102,101,628,10765,200,30,2,4,106
top,В,DP 572,SVO,ШЕРЕМЕТЬЕВО,RA73651,2025-01-18 22:57:00,C12Y75,SU9,Domestic,J,106A
freq,5642,32,1703,1703,165,3,2360,3378,9370,9667,553

In [157]:
df.select_dtypes(include=['float64']).describe()

ValueError: Cannot describe a DataFrame without columns

In [100]:
group = df[['Код АП']].value_counts(normalize=True)*100
round(group.head(10),1)

Код АП
SVO       15.1
VKO        9.3
KGD        5.9
AER        3.9
KZN        3.2
MMK        2.9
SVX        2.8
ARH        2.8
KUF        2.4
UFA        2.2
Name: proportion, dtype: float64

In [101]:
domestic_flights = df[df['Направление'] == 'Domestic']
group = df[['Код АП']].value_counts(normalize=True)*100
round(group.head(10),1)

Код АП
SVO       15.1
VKO        9.3
KGD        5.9
AER        3.9
KZN        3.2
MMK        2.9
SVX        2.8
ARH        2.8
KUF        2.4
UFA        2.2
Name: proportion, dtype: float64

In [162]:
domestic_flights = df[df['Направление'] == 'Domestic']
international_flights = df[df['Направление'] == 'International']
group_1 = domestic_flights[['Код АП']].value_counts()
roup_2 = international_flights[['Код АП']].value_counts()

group_1.head(1)

Код АП
SVO       1703
Name: count, dtype: int64